server:
    port: 8080
spring:
    datasource:
        url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf-8
        username: root
        password: qingxin
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        commons-log.connection-logger-name: stat,log4j
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM t_user
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    mvc:
        view:
            prefix: /jsp/
            suffix: .jsp
        multipart:
            enabled: true
            max-file-size: 50mb
            max-request-size: 50mb
mybatis:
    #扫描[mapper].xml文件
    mapper-locations:classpath: mapper/*.xml  
    #扫描类注解为Mapper的mapper文件所在的包  
    type-aliases-package: com.cn.model  
     
